name: C/C++ CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: glew setup
      run: sudo apt-get install libglew-dev
    - name: sdl2 setup
      run: sudo apt-get install libsdl2-dev
    - name: expat setup
      run: sudo apt-get install libexpat1-dev
    - name: png setup
      run: sudo apt-get install libpng-dev
    - name: gtest setup
      run: sudo apt-get install libgtest-dev
    - name: autoreconf
      run: autoreconf -iv
    - name: configure
      run: CFLAGS="--coverage" CXXFLAGS="--coverage" LDFLAGS="--coverage" ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: install gcovr
      run: sudo apt-get install gcovr
    - name: gcovr
      run: |
        mkdir -p coverage
        gcovr -r . --xml-pretty -o coverage/coverage.xml --gcov-ignore-errors no_working_dir_found
    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
    - name: make distcheck
      run: make distcheck
