name: C/C++ CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: glew setup
      run: sudo apt install libglew-dev
    - name: sdl2 setup
      run: sudo apt install libsdl2-dev
    - name: expat setup
      run: sudo apt install libexpat1-dev   
    - name: autoreconf
      run: autoreconf -iv
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
