name: C/C++ CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: glew setup
      run: sudo apt-get install libglew-dev
    - name: sdl2 setup
      run: sudo apt-get install libsdl2-dev
    - name: expat setup
      run: sudo apt-get install libexpat1-dev
    - name: png setup
      run: sudo apt-get install libpng-dev
    - name: gtest setup
      run: sudo apt-get install libgtest-dev
    - name: install gcovr
      run: sudo apt-get install gcovr
    - name: install lcov
      run: sudo apt-get install lcov
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure --enable-code-coverage
    - name: make
      run: make
    - name: make check-code-coverage
      run: make check-code-coverage
    - name: gcovr
      run: |
        mkdir -p coverage
        gcovr -r . --html-details -o coverage/coverage.html --gcov-ignore-errors no_working_dir_found \
          --exclude 'third_party/.*'
    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
    - name: make distcheck
      run: make distcheck
